# Generated by Django 4.2.11 on 2024-05-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gpass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('tracknumber', models.CharField(blank=True, max_length=20, unique=True)),
                ('reason', models.CharField(max_length=100)),
                ('specific', models.CharField(max_length=300)),
                ('requestor', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('departure', models.TextField(default='')),
                ('returns', models.TextField(default='')),
                ('to', models.IntegerField(default=0)),
                ('venue', models.TextField(default='')),
                ('signedBy', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('datesubmitted', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
