# Generated by Django 4.2.11 on 2024-05-02 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_alter_office_numusers'),
        ('accounts', '0002_useraccount_acc_lvl_alter_useraccount_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offices.office'),
        ),
    ]
