# Generated by Django 4.2.11 on 2024-05-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccount_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='office',
            field=models.IntegerField(default=10),
        ),
    ]
