# Generated by Django 4.2.11 on 2024-05-06 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_alter_office_region'),
        ('accounts', '0004_alter_useraccount_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offices.office'),
        ),
    ]
