# Generated by Django 4.2.11 on 2024-04-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('tracknumber', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('requestor', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('to', models.IntegerField()),
                ('message', models.TextField()),
                ('remarks', models.CharField(default='ok', max_length=100)),
                ('datesubmitted', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
