# Generated by Django 4.2.11 on 2024-04-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('tracknumber', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('requestor', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('to', models.IntegerField(default=0)),
                ('signedBy', models.IntegerField(default=0)),
                ('message', models.TextField(default='')),
                ('remarks', models.CharField(default='', max_length=100)),
                ('datesubmitted', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
    ]
