# Generated by Django 4.2.11 on 2024-04-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('officeID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('officeMail', models.EmailField(max_length=255)),
                ('street', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('province', models.CharField(max_length=300)),
                ('region', models.CharField(max_length=300)),
                ('numUsers', models.IntegerField(default=0)),
            ],
        ),
    ]
