# Generated by Django 4.2.11 on 2024-05-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_alter_office_numusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='region',
            field=models.TextField(),
        ),
    ]
