# Generated by Django 4.2.11 on 2024-05-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_alter_office_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='region',
            field=models.CharField(max_length=300),
        ),
    ]
